eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
  instance:
    #hostname: service-registry
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  metrics:
    enabled: true

logging:
  pattern:
    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

