spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: "%5p app_name=[${spring.producer.name:} trace_id=%mdc{trace_id:-} span_id=%mdc{span_id:-} trace_flags=%mdc{trace_flags} %p]"

---

spring:
  config:
    activate:
      on-profile:
      - docker
  cloud:
    config:
        enabled: true
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
  instance:
    #hostname: service-registry
    prefer-ip-address: true



